datasets:
  scannet_detection:  # for poitn cloud detection
    build_info:
      root_dir: "/mnt_jianchong/datasets/lavis/scannet_train_detection_data/"
      meta_data_dir: "/mnt_jianchong/votenet-main/scannet/meta_data/"
      split: ["train"]
      num_points: 40000
      use_color: False  # be consistent with model.detection_3d.use_color
      use_height: False
      augment: True
      use_random_cuboid: True
      random_cuboid_min_points: 30000
      max_num_obj: 64 # be consistent with model.detection_3d.max_num_obj
  